export default [
  {
    slug: 'grammar-complex-sentences',
    section: 'grammar',
    title: 'Сложные предложения для 7.0',
    level: 'B1–B2',
    minutes: 15,
    summary: 'Придаточные, причастные обороты и уступка: как показать Grammatical Range.',
    blocks: [
      { t: 'p', text: 'Для 7.0 нужно, чтобы в тексте регулярно встречались сложные предложения, причём в основном без ошибок. Вот пять конструкций, которые легко освоить.' },
      { t: 'h', text: '1. Relative clauses (which, who, where)' },
      { t: 'example', en: 'Cities which invest in public transport tend to have cleaner air.', ru: 'Города, которые вкладываются в общественный транспорт...' },
      { t: 'p', text: 'Запятая перед which ставится, когда информация дополнительная: "Paris, which I visited last year, is..."' },
      { t: 'h', text: '2. Уступка: although / while / despite' },
      { t: 'example', en: 'Although online learning is convenient, it requires a great deal of self-discipline.\nDespite being convenient, online learning requires self-discipline.', ru: 'После despite ставится существительное или -ing, а не полное предложение.' },
      { t: 'h', text: '3. Условные предложения' },
      { t: 'example', en: 'If governments taxed sugary drinks, consumption would fall.\nHad the policy been introduced earlier, fewer people would have been affected.', ru: '2-й тип для гипотез, 3-й (с инверсией) для прошлого.' },
      { t: 'h', text: '4. Причастные обороты' },
      { t: 'example', en: 'Faced with rising costs, many families are moving to the suburbs.', ru: 'Столкнувшись с ростом расходов...' },
      { t: 'h', text: '5. Пассив для академического тона' },
      { t: 'example', en: 'It is widely believed that... / The data was collected over ten years.', ru: '' },
      { t: 'warn', title: 'Не перегружайте', text: 'Предложения длиной 40+ слов чаще содержат ошибки. Чередуйте сложные и простые предложения.' },
    ],
    quiz: [
      { type: 'mc', q: 'Выберите правильный вариант: "____ the rain, the match continued."', options: ['Although', 'Despite', 'Even', 'However'], answer: 1, explain: 'После despite идёт существительное (the rain).' },
      { type: 'mc', q: '"If more people ____ bicycles, traffic would decrease."', options: ['use', 'used', 'will use', 'would use'], answer: 1, explain: 'Второй тип условных: If + Past Simple, would + V.' },
      { type: 'gap', q: 'Вставьте местоимение: "The scientist ____ discovered the vaccine received an award."', answer: ['who', 'that'] },
    ],
  },
  {
    slug: 'grammar-articles',
    section: 'grammar',
    title: 'Артикли: главная ошибка русскоговорящих',
    level: 'A2–B2',
    minutes: 14,
    summary: 'Основные правила a / an / the / нулевого артикля с примерами из эссе.',
    blocks: [
      { t: 'p', text: 'Ошибки в артиклях встречаются почти у всех, у кого в родном языке нет артиклей. Одна-две не критичны, а систематические снижают Grammatical Accuracy.' },
      { t: 'table', head: ['Артикль', 'Когда', 'Пример'], rows: [
        ['a / an', 'Один из многих, впервые упоминаем, исчисляемое в ед. числе', 'a serious problem, an increase'],
        ['the', 'Конкретный, единственный, уже упомянутый, превосходная степень', 'the government, the internet, the highest'],
        ['—', 'Общее понятие во мн. числе или неисчисляемое', 'Children need exercise. Pollution is...'],
      ] },
      { t: 'h', text: 'Частые ошибки в эссе' },
      { t: 'list', items: [
        '✗ "The technology changes our lives." → ✓ "Technology changes our lives." (в общем смысле)',
        '✗ "It is important problem." → ✓ "It is an important problem."',
        '✗ "in the 2010" → ✓ "in 2010", но "in the 1990s"',
        '✓ "the number of students rose", но "a number of students said..." (= несколько)',
        '✓ "the elderly", "the unemployed" (группы людей)',
      ] },
      { t: 'tip', title: 'Проверка', text: 'Перед сдачей эссе проверьте каждое исчисляемое существительное в единственном числе: перед ним должен стоять артикль или другое определяющее слово (my, this, every).' },
    ],
    quiz: [
      { type: 'mc', q: '"____ unemployment is a major issue in many regions."', options: ['A', 'The', '— (без артикля)'], answer: 2 },
      { type: 'mc', q: '"The graph shows ____ number of tourists between 2000 and 2020."', options: ['a', 'the', '—'], answer: 1 },
      { type: 'mc', q: '"This is ____ effective solution."', options: ['a', 'an', 'the'], answer: 1 },
    ],
  },
  {
    slug: 'grammar-tenses-graphs',
    section: 'grammar',
    title: 'Времена в Task 1 и Speaking',
    level: 'A2–B1',
    minutes: 10,
    summary: 'Past Simple, Present Perfect и прогнозы: какое время выбирать.',
    blocks: [
      { t: 'table', head: ['Ситуация', 'Время', 'Пример'], rows: [
        ['График за прошлый период', 'Past Simple', 'Sales rose by 20% in 2015.'],
        ['Период до настоящего момента', 'Present Perfect', 'Since 2010 the figure has doubled.'],
        ['Прогноз на графике', 'will / is expected to / is projected to', 'The population is projected to reach 9 million by 2040.'],
        ['Процесс, схема', 'Present Simple + пассив', 'The leaves are dried and then crushed.'],
        ['Опыт в Speaking', 'Present Perfect', 'I\'ve been to Italy twice.'],
      ] },
      { t: 'warn', title: 'Не путайте', text: 'С конкретной датой в прошлом ("in 2015", "last year") Present Perfect не используется.' },
    ],
    quiz: [
      { type: 'mc', q: '"In 2005 the number of cars ____ to 2 million."', options: ['has risen', 'rose', 'rises', 'is rising'], answer: 1 },
      { type: 'mc', q: '"By 2050 the figure ____ to exceed 50%."', options: ['expected', 'is expected', 'has expected', 'expects'], answer: 1 },
    ],
  },
  {
    slug: 'vocabulary-collocations',
    section: 'vocabulary',
    title: 'Коллокации и связки для Writing и Speaking',
    level: 'B1–B2',
    minutes: 12,
    summary: 'Устойчивые сочетания, которые повышают Lexical Resource, и связки без перебора.',
    blocks: [
      { t: 'p', text: 'Lexical Resource оценивает не «сложные слова», а точность и естественность. Коллокации, то есть слова, которые носители используют вместе, дают больше, чем редкие синонимы.' },
      { t: 'table', head: ['Вместо', 'Скажите'], rows: [
        ['make a crime', 'commit a crime'],
        ['do a decision', 'make a decision'],
        ['big rain', 'heavy rain'],
        ['strong problem', 'serious / major problem'],
        ['give attention', 'pay attention'],
        ['make research', 'do / conduct research'],
        ['solve a role', 'play a role'],
        ['get knowledge', 'gain / acquire knowledge'],
      ] },
      { t: 'h', text: 'Связки по функции' },
      { t: 'table', head: ['Функция', 'Связки'], rows: [
        ['Добавление', 'In addition, Moreover, What is more, Not only... but also'],
        ['Контраст', 'However, On the other hand, Nevertheless, Whereas'],
        ['Причина / следствие', 'As a result, Consequently, This leads to, Due to'],
        ['Пример', 'For instance, A case in point is, Such as'],
        ['Вывод', 'In conclusion, Overall, To sum up'],
      ] },
      { t: 'tip', title: 'Меньше значит лучше', text: 'Используйте связку в начале абзаца и 1–2 внутри. Связывайте предложения также через местоимения: "This trend...", "Such policies...".' },
    ],
    quiz: [
      { type: 'mc', q: 'Правильная коллокация:', options: ['do a mistake', 'make a mistake', 'create a mistake', 'take a mistake'], answer: 1 },
      { type: 'mc', q: 'Какая связка вводит контраст?', options: ['Moreover', 'Consequently', 'Nevertheless', 'For instance'], answer: 2 },
    ],
  },
];
