export default [
  {
    slug: 'listening-form-completion',
    section: 'listening',
    title: 'Part 1: заполнение форм, числа и написание слов',
    level: 'A2–B1',
    minutes: 15,
    summary: 'Как не терять лёгкие баллы в первой части: алфавит, числа, даты, адреса и инструкции по количеству слов.',
    blocks: [
      { t: 'p', text: 'Part 1 обычно самая простая, и здесь нужно набирать почти максимум. Чаще всего это телефонный разговор, где один человек записывает данные другого: имя, адрес, дату, стоимость.' },
      { t: 'h', text: 'Читайте инструкцию' },
      { t: 'p', text: 'Фраза **Write ONE WORD AND/OR A NUMBER** означает: одно слово, одно число или слово плюс число. Если в ответе два слова, он засчитывается как неверный, даже если смысл правильный.' },
      { t: 'example', en: 'Write NO MORE THAN TWO WORDS: "the old bridge" (3 слова) — неверно; "old bridge" — верно.', ru: 'Артикли тоже считаются словами.' },
      { t: 'h', text: 'Алфавит и спеллинг' },
      { t: 'p', text: 'Имена и улицы часто диктуют по буквам. Трудные пары для русскоговорящих:' },
      { t: 'table', head: ['Буквы', 'Как звучат', 'Чем легко спутать'], rows: [
        ['A / E / I', '/eɪ/, /iː/, /aɪ/', 'E путают с I'],
        ['G / J', '/dʒiː/, /dʒeɪ/', 'Друг с другом'],
        ['V / W', '/viː/, /ˈdʌbəl juː/', 'W называют double U'],
        ['Q / U', '/kjuː/, /juː/', 'Звучат похоже в конце'],
        ['R', '/ɑː/', 'Не похоже на русское «эр»'],
      ] },
      { t: 'p', text: 'Слышите **double** перед буквой или цифрой? Значит, она повторяется: "double T" = TT, "double five" = 55.' },
      { t: 'h', text: 'Числа и даты' },
      { t: 'list', items: [
        '**13 / 30, 14 / 40, 15 / 50**: в thirteen ударение на конце, в thirty в начале.',
        '**0** в телефонах читается как "oh".',
        'Дату можно писать как 3 March или March 3rd, оба варианта засчитываются.',
        'Цены: "twelve fifty" = 12.50, "a hundred and five" = 105.',
      ] },
      { t: 'h', text: 'Типичные слова, в которых ошибаются' },
      { t: 'p', text: 'accommodation, Wednesday, February, library, necessary, restaurant, environment, government, schedule, receipt, calendar, temperature, occasionally.' },
      { t: 'tip', title: 'Стратегия', text: 'За 30 секунд до записи пройдитесь по пропускам и подпишите карандашом, что ожидаете: число, имя, дату, существительное. Мозг будет «ловить» нужную информацию.' },
      { t: 'warn', title: 'Ловушка исправления', text: 'Собеседник может сказать "It\'s on the 15th... oh no, sorry, the 16th". Правильный ответ всегда последний.' },
    ],
    quiz: [
      { type: 'mc', q: 'Инструкция: NO MORE THAN TWO WORDS. Какой ответ НЕ засчитают?', options: ['city centre', 'the city centre', 'centre', 'centre 5'], answer: 1, explain: 'Артикль the считается словом, получается три слова.' },
      { type: 'gap', q: 'Вы слышите: "My postcode is B-double-S, five-oh-two". Запишите индекс без пробелов.', answer: ['BSS502', 'BSS 502'], explain: 'double S = SS, oh = 0.' },
      { type: 'gap', q: 'Правильно напишите слово «проживание, жильё» (a-c-c-o-…).', answer: ['accommodation'], explain: 'Две c и две m: accommodation.' },
      { type: 'mc', q: '"The fee is fifteen... sorry, fifty pounds." Что писать?', options: ['15', '50', '15 or 50', '65'], answer: 1 },
    ],
  },
  {
    slug: 'listening-distractors',
    section: 'listening',
    title: 'Дистракторы и перефразирование',
    level: 'B1–B2',
    minutes: 15,
    summary: 'Почему вы слышите все варианты ответа и как определить правильный.',
    blocks: [
      { t: 'p', text: 'В multiple choice спикеры обычно упоминают все три варианта, но только один подходит. Неправильные варианты называются дистракторами.' },
      { t: 'h', text: 'Три главных приёма составителей' },
      { t: 'ol', items: [
        '**Отказ или исправление.** "We thought about going by train, but in the end we took the coach."',
        '**Условие.** "The museum would be ideal if it weren\'t closed on Mondays."',
        '**Другой человек.** "My sister loves jazz, but personally I prefer classical."',
      ] },
      { t: 'h', text: 'Перефразирование' },
      { t: 'p', text: 'Вопрос и запись почти никогда не используют одни и те же слова. Тренируйтесь подбирать синонимы заранее.' },
      { t: 'table', head: ['В вопросе', 'В записи'], rows: [
        ['cheap', 'it won\'t cost much / reasonably priced'],
        ['the most popular', 'what most people go for'],
        ['difficult', 'challenging / not straightforward'],
        ['start', 'kick off / get under way'],
        ['not allowed', 'prohibited / you can\'t'],
      ] },
      { t: 'h', text: 'Слова-сигналы' },
      { t: 'p', text: 'Особенно внимательно слушайте после: **but, however, actually, in fact, unfortunately, although, the thing is**. Именно после них обычно звучит правильный ответ.' },
      { t: 'tip', title: 'Тренировка', text: 'После каждого теста откройте транскрипт и подчеркните фразу с правильным ответом и фразы с дистракторами. Так вы быстро научитесь узнавать шаблоны.' },
    ],
    quiz: [
      { type: 'mc', q: '"I was going to choose the history course, but the timetable didn\'t suit me, so I signed up for art instead." Какой курс выбран?', options: ['History', 'Art', 'Both', 'Neither'], answer: 1 },
      { type: 'mc', q: '"Most visitors go for the guided tour, although the audio guide is better value." Что самое популярное?', options: ['Audio guide', 'Guided tour', 'Self-guided walk', 'Неизвестно'], answer: 1, explain: '"what most visitors go for" = most popular.' },
      { type: 'mc', q: 'Какое слово чаще всего вводит правильный ответ?', options: ['and', 'also', 'however', 'so'], answer: 2 },
    ],
  },
  {
    slug: 'listening-maps',
    section: 'listening',
    title: 'Part 2: карты и планы',
    level: 'B1–B2',
    minutes: 12,
    summary: 'Лексика направлений и расположения, порядок работы с картой.',
    blocks: [
      { t: 'p', text: 'Задание с картой встречается в Part 2: вас «ведут» по территории (парк, музей, кампус), а вы подписываете объекты буквами.' },
      { t: 'h', text: 'Перед записью' },
      { t: 'list', items: [
        'Найдите точку старта: "You are here" или "Entrance".',
        'Отметьте стороны света, если они даны.',
        'Посмотрите, какие объекты уже подписаны: от них будут вести отсчёт.',
      ] },
      { t: 'h', text: 'Ключевая лексика' },
      { t: 'table', head: ['Фраза', 'Значение'], rows: [
        ['opposite', 'напротив'],
        ['adjacent to / next to', 'рядом, вплотную'],
        ['diagonally opposite', 'напротив по диагонали'],
        ['at the far end of', 'в дальнем конце'],
        ['to the left of / on your left', 'слева от / слева от вас'],
        ['just past / beyond', 'сразу за'],
        ['in the north-east corner', 'в северо-восточном углу'],
        ['go through / go across', 'пройти через / пересечь'],
        ['bear left / turn right', 'держитесь левее / поверните направо'],
      ] },
      { t: 'tip', title: 'Совет', text: 'Водите карандашом по карте вслед за голосом спикера. Если потеряли место, ориентируйтесь на следующий подписанный объект.' },
    ],
    quiz: [
      { type: 'mc', q: '"diagonally opposite" значит:', options: ['прямо напротив', 'напротив по диагонали', 'рядом', 'за углом'], answer: 1 },
      { type: 'mc', q: '"The café is just past the gift shop" означает, что кафе:', options: ['перед магазином', 'сразу за магазином', 'внутри магазина', 'напротив магазина'], answer: 1 },
    ],
  },
  {
    slug: 'listening-lectures',
    section: 'listening',
    title: 'Part 4: академические лекции',
    level: 'B2–C1',
    minutes: 15,
    summary: 'Как удержать нить лекции без пауз и заполнить конспект.',
    blocks: [
      { t: 'p', text: 'Part 4 звучит без перерыва около 4–5 минут, 10 вопросов подряд. Обычно это note completion: конспект лекции с пропусками.' },
      { t: 'h', text: 'Используйте структуру конспекта' },
      { t: 'p', text: 'Заголовки конспекта повторяют структуру лекции. Когда лектор говорит "Moving on to...", "Another factor...", "Finally...", он переходит к следующему заголовку.' },
      { t: 'h', text: 'Сигнальные фразы лектора' },
      { t: 'table', head: ['Функция', 'Фразы'], rows: [
        ['Начало темы', 'Today I\'d like to look at... / Let\'s begin with...'],
        ['Пример', 'For instance... / Take the case of...'],
        ['Важная мысль', 'What\'s crucial here is... / The key point is...'],
        ['Контраст', 'On the other hand... / Conversely...'],
        ['Вывод', 'To sum up... / So what this tells us is...'],
      ] },
      { t: 'h', text: 'Что обычно пропущено' },
      { t: 'p', text: 'В 80% случаев пропуск это существительное. Проверяйте грамматику: если перед пропуском стоит "a", слово начинается с согласной и стоит в единственном числе; если "many", нужно множественное число.' },
      { t: 'warn', title: 'Частая ошибка', text: 'Забытое окончание -s во множественном числе делает ответ неверным. Прочитайте предложение с вашим ответом целиком.' },
      { t: 'tip', title: 'Если пропустили ответ', text: 'Не останавливайтесь. Сразу переходите к следующему пропуску, иначе потеряете ещё 2–3 ответа. Вернуться можно в конце по смыслу.' },
    ],
    quiz: [
      { type: 'mc', q: 'Конспект: "Bees use the sun as a ____ to navigate." Какое слово грамматически подходит?', options: ['guide', 'guides', 'guiding', 'guided'], answer: 0, explain: 'После "a" нужно существительное в единственном числе.' },
      { type: 'mc', q: 'Лектор говорит "Moving on to...". Что это значит?', options: ['Он делает вывод', 'Он переходит к новому пункту', 'Он приводит пример', 'Он повторяет мысль'], answer: 1 },
    ],
  },
];
