export default [
  {
    slug: 'reading-skimming-scanning',
    section: 'reading',
    title: 'Skimming и scanning: как читать быстро',
    level: 'B1',
    minutes: 12,
    summary: 'Две техники, без которых невозможно уложиться в 60 минут.',
    blocks: [
      { t: 'p', text: 'На 2 750 слов и 40 вопросов у вас 60 минут. Читать каждое слово не нужно: нужно знать, где искать.' },
      { t: 'h', text: 'Skimming: общая картина за 2–3 минуты' },
      { t: 'list', items: [
        'Прочитайте заголовок и подзаголовок.',
        'Прочитайте первое предложение каждого абзаца: обычно в нём главная мысль.',
        'Набросайте рядом с абзацем 2–3 слова о чём он.',
      ] },
      { t: 'h', text: 'Scanning: поиск конкретики' },
      { t: 'p', text: 'Ищите «якоря», которые легко заметить глазами: имена собственные, даты, числа, слова с заглавной буквы, термины в кавычках. Найдя якорь, внимательно читайте 2–3 предложения вокруг.' },
      { t: 'example', en: 'Question: "In which year did the first public library open in the city?"', ru: 'Якорь: год (четыре цифры). Ищите числа, затем проверяйте контекст.' },
      { t: 'h', text: 'Распределение времени' },
      { t: 'table', head: ['Текст', 'Время', 'Комментарий'], rows: [
        ['Passage 1', '17 минут', 'Набирайте баллы быстро'],
        ['Passage 2', '20 минут', ''],
        ['Passage 3', '23 минуты', 'Самый сложный текст'],
      ] },
      { t: 'tip', title: 'Порядок вопросов', text: 'Начинайте с заданий, где ответы идут по порядку текста (TFNG, completion). Matching headings удобнее делать после, когда текст уже знаком.' },
    ],
    quiz: [
      { type: 'mc', q: 'Где чаще всего находится главная мысль абзаца?', options: ['В последнем предложении', 'В первом предложении', 'В середине', 'В подзаголовке'], answer: 1 },
      { type: 'mc', q: 'Что лучше всего использовать как «якорь» для scanning?', options: ['Союзы', 'Числа и имена собственные', 'Артикли', 'Местоимения'], answer: 1 },
    ],
  },
  {
    slug: 'reading-tfng',
    section: 'reading',
    title: 'True / False / Not Given без ошибок',
    level: 'B1–B2',
    minutes: 18,
    summary: 'Самый «коварный» тип вопросов: чёткое правило различия False и Not Given.',
    blocks: [
      { t: 'p', text: 'Это задание проверяет, понимаете ли вы, что именно утверждает текст. Отвечайте только по тексту, а не по своим знаниям о мире.' },
      { t: 'table', head: ['Ответ', 'Когда ставить'], rows: [
        ['TRUE', 'Текст говорит то же самое, другими словами.'],
        ['FALSE', 'Текст прямо противоречит утверждению.'],
        ['NOT GIVEN', 'В тексте нет информации, чтобы подтвердить или опровергнуть.'],
      ] },
      { t: 'p', text: 'Для мнений автора используется вариант **Yes / No / Not Given**, логика та же.' },
      { t: 'h', text: 'Разберём на примере' },
      { t: 'example', en: 'Text: "The bridge, completed in 1890, was the longest in Europe for nearly two decades."', ru: '' },
      { t: 'list', items: [
        '"The bridge was finished in the 19th century." → **TRUE** (1890 = 19 век).',
        '"The bridge was the longest in the world." → **NOT GIVEN** (про мир ничего не сказано).',
        '"The bridge held its European record for over thirty years." → **FALSE** (nearly two decades ≈ 20 лет).',
      ] },
      { t: 'h', text: 'Слова, которые меняют смысл' },
      { t: 'p', text: 'Обращайте внимание на квантификаторы и модальность: **all / some / most, always / often / never, may / must, the first / the only**. Если в утверждении "all", а в тексте "many", ответ скорее FALSE или NOT GIVEN.' },
      { t: 'warn', title: 'Главная ловушка', text: 'Если вы думаете «это, наверное, правда, потому что логично», а прямого подтверждения в тексте нет, ответ NOT GIVEN.' },
      { t: 'tip', title: 'Алгоритм', text: '1) Найдите ключевое слово утверждения. 2) Найдите место в тексте. 3) Сравните каждую часть утверждения: кто, что, когда, сколько. Если всё совпадает, TRUE; если что-то противоречит, FALSE; если чего-то нет, NOT GIVEN.' },
    ],
    quiz: [
      { type: 'mc', q: 'Text: "Most of the volunteers were students." Statement: "All of the volunteers were students."', options: ['TRUE', 'FALSE', 'NOT GIVEN'], answer: 1, explain: 'most ≠ all: текст противоречит утверждению.' },
      { type: 'mc', q: 'Text: "The festival attracted 20,000 visitors in its first year." Statement: "The festival was more popular in its second year."', options: ['TRUE', 'FALSE', 'NOT GIVEN'], answer: 2, explain: 'Про второй год ничего не сказано.' },
      { type: 'mc', q: 'Text: "Researchers were unable to find any evidence supporting the theory." Statement: "The theory has not been proven."', options: ['TRUE', 'FALSE', 'NOT GIVEN'], answer: 0 },
    ],
  },
  {
    slug: 'reading-headings',
    section: 'reading',
    title: 'Matching headings',
    level: 'B2',
    minutes: 14,
    summary: 'Как подбирать заголовки к абзацам и не попадаться на совпадение слов.',
    blocks: [
      { t: 'p', text: 'Вам дают список заголовков (их больше, чем абзацев) и просят подобрать к каждому абзацу тот, что описывает его **главную** мысль.' },
      { t: 'h', text: 'Пошаговая стратегия' },
      { t: 'ol', items: [
        'Сначала прочитайте все заголовки и подчеркните в каждом ключевое слово.',
        'Прочитайте абзац: первое предложение, последнее и пробегите середину.',
        'Сформулируйте главную мысль своими словами в 3–5 словах.',
        'Выберите заголовок, который совпадает по смыслу, а не по отдельным словам.',
        'Начинайте с коротких абзацев и с тех, где уверены.',
      ] },
      { t: 'warn', title: 'Ловушка', text: 'Заголовок, в котором есть слово прямо из абзаца, часто неверный. Он описывает деталь, а не главную мысль.' },
      { t: 'example', en: 'Paragraph: "While the scheme was praised at first, critics soon pointed out that it had failed to reduce traffic in the city centre, and costs had doubled."', ru: 'Неверно: "Praise for the scheme" (это деталь). Верно: "Problems with the scheme".' },
    ],
    quiz: [
      { type: 'mc', q: 'Что должен отражать заголовок?', options: ['Самый интересный факт абзаца', 'Главную мысль абзаца', 'Первое слово абзаца', 'Пример из абзаца'], answer: 1 },
    ],
  },
  {
    slug: 'reading-completion',
    section: 'reading',
    title: 'Summary и sentence completion',
    level: 'B1–B2',
    minutes: 12,
    summary: 'Заполнение пропусков словами из текста: грамматика, лимит слов и поиск по синонимам.',
    blocks: [
      { t: 'p', text: 'Нужно вставить слова из текста в краткое изложение или предложения. Иногда даётся список слов (word box), иногда слова берутся прямо из текста.' },
      { t: 'h', text: 'Алгоритм' },
      { t: 'ol', items: [
        'Проверьте лимит: ONE WORD ONLY, NO MORE THAN TWO WORDS.',
        'Определите часть речи пропуска по соседним словам.',
        'Найдите в тексте фрагмент, который пересказывает summary (обычно один-два абзаца).',
        'Скопируйте слово точно как в тексте, включая единственное и множественное число.',
      ] },
      { t: 'tip', title: 'Word box', text: 'Если дан список слов, часто несколько из них подходят грамматически. Выбирайте по смыслу и вычёркивайте использованные.' },
      { t: 'warn', title: 'Не меняйте форму', text: 'Если в тексте "pollution", а вы пишете "polluted", ответ неверный.' },
    ],
    quiz: [
      { type: 'mc', q: '"The study found that regular ____ improved memory." Какая часть речи нужна?', options: ['Глагол', 'Существительное', 'Наречие', 'Предлог'], answer: 1, explain: 'После прилагательного regular нужно существительное (exercise, sleep...).' },
    ],
  },
];
