export default [
  {
    slug: 'speaking-part1',
    section: 'speaking',
    title: 'Part 1: ответы, которые звучат естественно',
    level: 'A2–B2',
    minutes: 12,
    summary: 'Формула ответа из трёх шагов и типичные темы первой части.',
    blocks: [
      { t: 'p', text: 'Part 1 это разминка: вопросы о вас и повседневной жизни. Ответ из одного слова звучит бедно, монолог на минуту лишний. Оптимально 2–3 предложения.' },
      { t: 'h', text: 'Формула A + R + E' },
      { t: 'list', items: [
        '**Answer**: прямой ответ.',
        '**Reason**: почему.',
        '**Example / Extra**: пример или деталь.',
      ] },
      { t: 'example', en: 'Q: Do you like cooking?\nA: Yes, I really enjoy it, especially at the weekends. It helps me unwind after a busy week, and lately I\'ve been experimenting with Thai recipes, which are surprisingly simple.', ru: 'Ответ + причина + деталь.' },
      { t: 'h', text: 'Частые темы' },
      { t: 'p', text: 'Work or studies, hometown, home, family, hobbies, music, reading, sport, weather, food, transport, holidays, technology, friends, shopping.' },
      { t: 'h', text: 'Фразы, которые помогают выиграть время' },
      { t: 'list', items: [
        'That\'s an interesting question...',
        'I\'ve never really thought about it, but I suppose...',
        'Well, it depends on...',
        'To be honest...',
      ] },
      { t: 'warn', title: 'Не заучивайте ответы', text: 'Экзаменатор сразу замечает заученный текст по интонации и может прервать вас или задать неожиданный вопрос.' },
    ],
    quiz: [
      { type: 'mc', q: 'Какая длина ответа в Part 1 оптимальна?', options: ['Одно слово', '2–3 предложения', '1 минута', '2 минуты'], answer: 1 },
    ],
  },
  {
    slug: 'speaking-part2',
    section: 'speaking',
    title: 'Part 2: монолог по карточке на 2 минуты',
    level: 'B1–B2',
    minutes: 15,
    summary: 'Как использовать минуту подготовки и говорить две минуты без пауз.',
    blocks: [
      { t: 'p', text: 'Вы получаете карточку с темой и тремя-четырьмя подсказками. 1 минута на подготовку, затем 1–2 минуты речи. Экзаменатор остановит вас через 2 минуты.' },
      { t: 'example', en: 'Describe a place you visited that you would like to go back to.\nYou should say:\n– where it is\n– when you went there\n– what you did there\nand explain why you would like to go back.', ru: '' },
      { t: 'h', text: 'Минута подготовки' },
      { t: 'p', text: 'Пишите только ключевые слова по каждому пункту: 3–4 слова на пункт. Полные предложения не успеете ни написать, ни прочитать.' },
      { t: 'h', text: 'Структура речи' },
      { t: 'ol', items: [
        'Вступление в одно предложение: "I\'d like to talk about...".',
        'Пункты карточки по порядку, по 20–25 секунд на каждый.',
        'Последний пункт ("explain why") раскройте больше всего: это самая ценная часть.',
        'Если время осталось, добавьте историю или чувства: "What I remember most is...".',
      ] },
      { t: 'tip', title: 'Метод 5 чувств', text: 'Если не хватает идей, опишите что вы видели, слышали, чувствовали, пробовали. Это сразу добавляет лексику и время.' },
      { t: 'h', text: 'Связки для монолога' },
      { t: 'p', text: 'As for..., Another thing worth mentioning is..., What really stood out was..., Looking back,..., The main reason why...' },
    ],
    quiz: [
      { type: 'mc', q: 'Как лучше использовать минуту подготовки?', options: ['Написать полный текст', 'Записать ключевые слова по каждому пункту', 'Ничего не писать', 'Выучить первое предложение'], answer: 1 },
      { type: 'mc', q: 'Какой пункт карточки обычно стоит раскрыть подробнее всего?', options: ['Первый', 'Where it is', 'Explain why...', 'Ни один'], answer: 2 },
    ],
  },
  {
    slug: 'speaking-part3',
    section: 'speaking',
    title: 'Part 3: дискуссия и абстрактные вопросы',
    level: 'B2–C1',
    minutes: 12,
    summary: 'Как отвечать на общие вопросы о обществе, сравнивать и рассуждать.',
    blocks: [
      { t: 'p', text: 'Вопросы в Part 3 касаются общества, а не лично вас: "Why do people...?", "How has... changed?", "What will... be like in the future?".' },
      { t: 'h', text: 'Формула ответа' },
      { t: 'list', items: [
        '**Позиция**: "I\'d say that..."',
        '**Объяснение**: "The main reason is..."',
        '**Пример**: "For instance, in my country..."',
        '**Другой взгляд**: "Having said that, some people might argue..."',
      ] },
      { t: 'h', text: 'Полезные приёмы' },
      { t: 'table', head: ['Приём', 'Фраза'], rows: [
        ['Прошлое и настоящее', 'Whereas a generation ago..., nowadays...'],
        ['Разные группы', 'It depends on the age group. Younger people tend to...'],
        ['Прогноз', 'I imagine that in the future... / It\'s likely that...'],
        ['Осторожность', 'It seems to me... / I\'m not entirely sure, but...'],
      ] },
      { t: 'example', en: 'Q: Why do some people prefer to travel abroad rather than in their own country?\nA: I\'d say the main draw is novelty. People want to experience a culture that is completely different from their own. For instance, many people from my city fly to Turkey not only because it\'s affordable, but because the food and the atmosphere feel exotic. Having said that, domestic travel has become more popular recently, partly because it\'s more convenient.', ru: '' },
    ],
    quiz: [
      { type: 'mc', q: 'Чем Part 3 отличается от Part 1?', options: ['Вопросы о вашей жизни', 'Абстрактные вопросы об обществе', 'Монолог по карточке', 'Чтение текста'], answer: 1 },
    ],
  },
  {
    slug: 'speaking-pronunciation',
    section: 'speaking',
    title: 'Произношение и беглость',
    level: 'Все уровни',
    minutes: 10,
    summary: 'Что значит Pronunciation на 7.0 и как говорить бегло без «эээ».',
    blocks: [
      { t: 'p', text: 'Акцент не снижает балл. Оценивают понятность: звуки, ударения, интонацию и связность речи.' },
      { t: 'h', text: 'Типичные проблемы русскоговорящих' },
      { t: 'list', items: [
        '**th** (/θ/, /ð/): think, this. Не заменяйте на «с» и «з».',
        '**w / v**: west ≠ vest.',
        '**долгие и краткие гласные**: ship / sheep, full / fool.',
        '**оглушение на конце**: bad ≠ bat, dog ≠ dock.',
        '**ровная интонация**: английская речь более «волнистая», ударные слова выделяются.',
      ] },
      { t: 'h', text: 'Беглость' },
      { t: 'p', text: 'Паузы для поиска мысли нормальны. Плохо, когда паузы для поиска слова или грамматики. Заменяйте «эээ» на fillers: "Well...", "Let me think...", "The thing is...".' },
      { t: 'tip', title: 'Упражнение shadowing', text: 'Включите короткую запись носителя (подкаст, TED), повторяйте за ним с отставанием в полсекунды, копируя интонацию. 10 минут в день заметно улучшают ритм речи.' },
    ],
    quiz: [
      { type: 'mc', q: 'Снижает ли акцент балл за Pronunciation?', options: ['Да, всегда', 'Нет, оценивается понятность', 'Только русский акцент', 'Только в Part 2'], answer: 1 },
    ],
  },
];
