export default [
  {
    slug: 'writing-criteria',
    section: 'writing',
    title: 'Как оценивают Writing: 4 критерия',
    level: 'Все уровни',
    minutes: 12,
    summary: 'Что именно проверяет экзаменатор и чем 6.0 отличается от 7.0.',
    blocks: [
      { t: 'p', text: 'Каждое задание оценивается по четырём равным критериям. Task 2 весит в два раза больше Task 1.' },
      { t: 'table', head: ['Критерий', 'Что проверяют', 'Для 7.0 нужно'], rows: [
        ['Task Response', 'Ответили ли на все части вопроса, есть ли ясная позиция', 'Позиция понятна во всём эссе, идеи развиты и подкреплены'],
        ['Coherence & Cohesion', 'Логика, абзацы, связки', 'Логичная структура, связки без перебора, одна идея на абзац'],
        ['Lexical Resource', 'Разнообразие и точность лексики', 'Менее частотная лексика, коллокации, редкие ошибки'],
        ['Grammatical Range & Accuracy', 'Разнообразие и точность грамматики', 'Сложные предложения, большинство предложений без ошибок'],
      ] },
      { t: 'h', text: 'Что тянет балл вниз' },
      { t: 'list', items: [
        'Ответ не на тот вопрос или только на часть вопроса.',
        'Нет позиции в opinion essay.',
        'Слишком много связок ("Moreover, Furthermore, In addition" подряд).',
        'Заученные фразы ("In this day and age...", "It is a well-known fact...").',
        'Меньше 250 / 150 слов.',
      ] },
      { t: 'tip', title: 'Быстрый рост', text: 'Самое быстрое улучшение даёт Task Response: перечитайте задание, подчеркните каждую часть вопроса и проверьте, что ответили на все.' },
    ],
    quiz: [
      { type: 'mc', q: 'Какое задание весит больше?', options: ['Task 1', 'Task 2', 'Одинаково'], answer: 1 },
      { type: 'mc', q: 'Что из этого снизит Coherence & Cohesion?', options: ['Одна идея на абзац', 'Чрезмерное количество связок', 'Topic sentence в начале абзаца', 'Местоимения для связи предложений'], answer: 1 },
    ],
  },
  {
    slug: 'writing-task2-structure',
    section: 'writing',
    title: 'Task 2: структура эссе на 7+',
    level: 'B1–B2',
    minutes: 20,
    summary: 'Универсальная структура из четырёх абзацев, план за 5 минут и пример введения.',
    blocks: [
      { t: 'h', text: 'Типы эссе' },
      { t: 'table', head: ['Тип', 'Как узнать', 'Что делать'], rows: [
        ['Opinion', 'To what extent do you agree or disagree?', 'Ясная позиция с первого абзаца'],
        ['Discussion', 'Discuss both views and give your own opinion.', 'Абзац на каждую сторону + ваше мнение'],
        ['Adv / Disadv', 'Do the advantages outweigh the disadvantages?', 'Сравнить и сказать, что перевешивает'],
        ['Problem / Solution', 'What problems... What solutions...?', 'Абзац на проблемы, абзац на решения'],
        ['Two-part', 'Why is this? Is it positive or negative?', 'Ответить на каждый вопрос'],
      ] },
      { t: 'h', text: 'Структура из четырёх абзацев' },
      { t: 'ol', items: [
        '**Введение (40–50 слов)**: перефразируйте тему + ваша позиция (thesis).',
        '**Body 1 (90–110 слов)**: topic sentence → объяснение → пример → связь с позицией.',
        '**Body 2 (90–110 слов)**: та же схема для второй идеи.',
        '**Заключение (30–40 слов)**: повторите позицию другими словами, без новых идей.',
      ] },
      { t: 'h', text: 'Пример' },
      { t: 'example', en: 'Task: Some people believe that university education should be free for everyone. To what extent do you agree or disagree?', ru: '' },
      { t: 'example', en: 'Introduction: "It is often argued that higher education ought to be funded entirely by the state. While this policy would place a considerable burden on taxpayers, I firmly believe that its long-term benefits to society justify the cost."', ru: 'Перефраз темы + уступка + чёткая позиция.' },
      { t: 'example', en: 'Topic sentence for Body 1: "The most compelling reason for free tuition is that it allows talent, rather than family wealth, to determine who receives a degree."', ru: '' },
      { t: 'h', text: 'План за 5 минут' },
      { t: 'list', items: [
        'Подчеркните ключевые слова и тип вопроса.',
        'Решите позицию (не обязательно «правильную», а ту, которую легче аргументировать).',
        'Запишите 2 основные идеи и по одному конкретному примеру.',
      ] },
      { t: 'tip', title: 'Пример должен быть конкретным', text: 'Не "many people think", а "a talented student from a low-income family would no longer have to choose between a degree and a full-time job". Пример должен показывать, как идея работает в жизни; выдуманная статистика не нужна.' },
    ],
    quiz: [
      { type: 'mc', q: '"Discuss both views and give your own opinion." Какой это тип?', options: ['Opinion', 'Discussion', 'Problem / Solution', 'Two-part'], answer: 1 },
      { type: 'mc', q: 'Что НЕ стоит делать в заключении?', options: ['Повторить позицию', 'Добавить новую идею', 'Коротко подвести итог', 'Использовать In conclusion'], answer: 1 },
    ],
  },
  {
    slug: 'writing-task1-academic',
    section: 'writing',
    title: 'Task 1 Academic: графики и диаграммы',
    level: 'B1–B2',
    minutes: 18,
    summary: 'Overview как главный ключ к баллу, лексика трендов и структура отчёта.',
    blocks: [
      { t: 'p', text: 'В Task 1 нужно описать данные, а не объяснять причины. Своё мнение не нужно.' },
      { t: 'h', text: 'Структура' },
      { t: 'ol', items: [
        '**Введение**: перефразируйте название графика (что, где, когда).',
        '**Overview**: 2 главные тенденции без цифр. Без overview балл за Task Achievement не выше 5.',
        '**Детали 1**: группа связанных данных с цифрами.',
        '**Детали 2**: вторая группа данных и сравнения.',
      ] },
      { t: 'h', text: 'Лексика трендов' },
      { t: 'table', head: ['Тренд', 'Глаголы', 'Существительные'], rows: [
        ['↑', 'rise, increase, grow, climb, surge', 'a rise, an increase, growth'],
        ['↓', 'fall, decline, drop, decrease, plunge', 'a fall, a decline, a drop'],
        ['→', 'remain stable, level off, plateau', 'a plateau'],
        ['↕', 'fluctuate', 'fluctuation'],
        ['вершина', 'peak at, reach a high of', 'a peak'],
      ] },
      { t: 'p', text: 'Наречия для степени: **slightly, gradually, steadily, considerably, significantly, sharply, dramatically**.' },
      { t: 'example', en: 'Overview: "Overall, car use rose steadily over the period, while the popularity of buses declined. Cycling remained the least common mode of transport throughout."', ru: 'Только главные тенденции, без цифр.' },
      { t: 'h', text: 'Сравнения' },
      { t: 'list', items: [
        'twice as many as / three times higher than',
        'just over a quarter (26%), roughly a third (33%), the vast majority (85%)',
        'X was the most popular, followed by Y',
        'whereas / while / by contrast',
      ] },
      { t: 'warn', title: 'Частая ошибка', text: 'Не перечисляйте каждую цифру. Экзаменатор хочет видеть выбор главного и сравнения.' },
    ],
    quiz: [
      { type: 'mc', q: 'Чего НЕ должно быть в overview?', options: ['Главных тенденций', 'Конкретных цифр', 'Сравнения категорий', 'Слова Overall'], answer: 1 },
      { type: 'gap', q: 'Вставьте существительное: "There was a sharp ____ in sales" (рост).', answer: ['rise', 'increase'] },
      { type: 'mc', q: '26% это:', options: ['just over a quarter', 'roughly a half', 'the vast majority', 'a third'], answer: 0 },
    ],
  },
  {
    slug: 'writing-task1-letter',
    section: 'writing',
    title: 'Task 1 General: письма',
    level: 'B1',
    minutes: 12,
    summary: 'Три тона письма, обязательные пункты и готовые фразы.',
    blocks: [
      { t: 'p', text: 'В задании всегда три пункта (bullet points). Каждый нужно раскрыть отдельным абзацем.' },
      { t: 'table', head: ['Тон', 'Кому', 'Начало', 'Конец'], rows: [
        ['Formal', 'Незнакомому, организации', 'Dear Sir or Madam,', 'Yours faithfully,'],
        ['Semi-formal', 'Знакомому по имени (начальник, сосед)', 'Dear Mr Brown,', 'Yours sincerely,'],
        ['Informal', 'Другу', 'Dear Anna, / Hi Tom,', 'Best wishes, / Love,'],
      ] },
      { t: 'h', text: 'Полезные фразы' },
      { t: 'list', items: [
        'Formal: "I am writing to complain about...", "I would be grateful if you could...", "I look forward to hearing from you."',
        'Informal: "It was great to hear from you!", "Guess what?", "Can\'t wait to see you!"',
      ] },
      { t: 'warn', title: 'Не смешивайте тон', text: 'Сокращения (I\'m, can\'t) и разговорные фразы допустимы только в неформальном письме.' },
    ],
    quiz: [
      { type: 'mc', q: 'Письмо начинается с "Dear Sir or Madam". Как закончить?', options: ['Yours sincerely', 'Yours faithfully', 'Best wishes', 'Cheers'], answer: 1 },
    ],
  },
];
