// Тематическая лексика для Writing Task 2 и Speaking Part 3.
export const vocabulary = [
  {
    id: 'education',
    title: 'Education',
    ru: 'Образование',
    words: [
      { en: 'curriculum', ru: 'учебная программа', ex: 'Coding should be part of the school curriculum.' },
      { en: 'tuition fees', ru: 'плата за обучение', ex: 'Rising tuition fees discourage many students.' },
      { en: 'rote learning', ru: 'зубрёжка', ex: 'Rote learning rarely develops critical thinking.' },
      { en: 'to acquire knowledge', ru: 'получать знания', ex: 'Children acquire knowledge through play.' },
      { en: 'vocational training', ru: 'профессиональное обучение', ex: 'Vocational training prepares students for specific jobs.' },
      { en: 'academic performance', ru: 'успеваемость', ex: 'Sleep has a direct effect on academic performance.' },
      { en: 'lifelong learning', ru: 'обучение на протяжении жизни', ex: 'Technology makes lifelong learning more accessible.' },
      { en: 'to drop out', ru: 'бросить учёбу', ex: 'Financial problems force some students to drop out.' },
      { en: 'well-rounded', ru: 'всесторонне развитый', ex: 'Sport helps produce well-rounded individuals.' },
      { en: 'distance learning', ru: 'дистанционное обучение', ex: 'Distance learning suits working adults.' },
    ],
  },
  {
    id: 'environment',
    title: 'Environment',
    ru: 'Экология',
    words: [
      { en: 'carbon emissions', ru: 'выбросы углерода', ex: 'Aviation is responsible for significant carbon emissions.' },
      { en: 'renewable energy', ru: 'возобновляемая энергия', ex: 'Governments should invest in renewable energy.' },
      { en: 'to deplete', ru: 'истощать', ex: 'Overfishing depletes ocean resources.' },
      { en: 'biodiversity', ru: 'биоразнообразие', ex: 'Deforestation is a major threat to biodiversity.' },
      { en: 'sustainable', ru: 'устойчивый, экологичный', ex: 'We need more sustainable forms of transport.' },
      { en: 'landfill', ru: 'свалка', ex: 'Most plastic waste ends up in landfill.' },
      { en: 'to mitigate', ru: 'смягчать', ex: 'Planting trees can mitigate the effects of heatwaves.' },
      { en: 'endangered species', ru: 'вымирающие виды', ex: 'Zoos can help protect endangered species.' },
      { en: 'carbon footprint', ru: 'углеродный след', ex: 'Eating less meat reduces your carbon footprint.' },
      { en: 'to raise awareness', ru: 'повышать осведомлённость', ex: 'Campaigns raise awareness of climate change.' },
    ],
  },
  {
    id: 'technology',
    title: 'Technology',
    ru: 'Технологии',
    words: [
      { en: 'cutting-edge', ru: 'передовой', ex: 'The hospital uses cutting-edge equipment.' },
      { en: 'to automate', ru: 'автоматизировать', ex: 'Many routine jobs will be automated.' },
      { en: 'screen time', ru: 'время у экрана', ex: 'Parents should limit children\'s screen time.' },
      { en: 'data privacy', ru: 'конфиденциальность данных', ex: 'Social networks raise concerns about data privacy.' },
      { en: 'tech-savvy', ru: 'разбирающийся в технике', ex: 'Young people are generally more tech-savvy.' },
      { en: 'to become obsolete', ru: 'устареть', ex: 'Some professions may become obsolete.' },
      { en: 'digital divide', ru: 'цифровое неравенство', ex: 'The digital divide affects rural communities.' },
      { en: 'breakthrough', ru: 'прорыв', ex: 'The vaccine was a major scientific breakthrough.' },
      { en: 'to rely on', ru: 'полагаться на', ex: 'We rely on smartphones for almost everything.' },
      { en: 'artificial intelligence', ru: 'искусственный интеллект', ex: 'Artificial intelligence is transforming medicine.' },
    ],
  },
  {
    id: 'health',
    title: 'Health',
    ru: 'Здоровье',
    words: [
      { en: 'sedentary lifestyle', ru: 'малоподвижный образ жизни', ex: 'A sedentary lifestyle increases the risk of disease.' },
      { en: 'balanced diet', ru: 'сбалансированное питание', ex: 'A balanced diet includes plenty of vegetables.' },
      { en: 'obesity', ru: 'ожирение', ex: 'Childhood obesity is rising in many countries.' },
      { en: 'life expectancy', ru: 'продолжительность жизни', ex: 'Life expectancy has increased dramatically.' },
      { en: 'preventive measures', ru: 'профилактические меры', ex: 'Preventive measures are cheaper than treatment.' },
      { en: 'mental well-being', ru: 'психологическое благополучие', ex: 'Exercise improves mental well-being.' },
      { en: 'to be prone to', ru: 'быть склонным к', ex: 'Older people are more prone to injuries.' },
      { en: 'healthcare system', ru: 'система здравоохранения', ex: 'An ageing population puts pressure on the healthcare system.' },
      { en: 'to cut down on', ru: 'сократить потребление', ex: 'Try to cut down on sugar.' },
      { en: 'junk food', ru: 'вредная еда', ex: 'Advertising junk food to children should be banned.' },
    ],
  },
  {
    id: 'work',
    title: 'Work',
    ru: 'Работа',
    words: [
      { en: 'job satisfaction', ru: 'удовлетворённость работой', ex: 'Salary is not the only factor in job satisfaction.' },
      { en: 'work-life balance', ru: 'баланс работы и жизни', ex: 'Remote work can improve work-life balance.' },
      { en: 'to be laid off', ru: 'быть уволенным (по сокращению)', ex: 'Hundreds of workers were laid off.' },
      { en: 'career prospects', ru: 'карьерные перспективы', ex: 'A degree improves career prospects.' },
      { en: 'unemployment rate', ru: 'уровень безработицы', ex: 'The unemployment rate fell to 4%.' },
      { en: 'to commute', ru: 'ездить на работу', ex: 'Many people commute for over an hour a day.' },
      { en: 'flexible hours', ru: 'гибкий график', ex: 'Flexible hours attract young professionals.' },
      { en: 'entrepreneur', ru: 'предприниматель', ex: 'Young entrepreneurs need access to funding.' },
      { en: 'burnout', ru: 'выгорание', ex: 'Long hours often lead to burnout.' },
      { en: 'to climb the career ladder', ru: 'продвигаться по карьерной лестнице', ex: 'She climbed the career ladder quickly.' },
    ],
  },
  {
    id: 'society',
    title: 'Society & Cities',
    ru: 'Общество и города',
    words: [
      { en: 'urbanisation', ru: 'урбанизация', ex: 'Rapid urbanisation causes housing shortages.' },
      { en: 'traffic congestion', ru: 'пробки', ex: 'Traffic congestion costs the economy billions.' },
      { en: 'affordable housing', ru: 'доступное жильё', ex: 'Young people struggle to find affordable housing.' },
      { en: 'ageing population', ru: 'стареющее население', ex: 'An ageing population means fewer workers.' },
      { en: 'crime rate', ru: 'уровень преступности', ex: 'Better lighting can reduce the crime rate.' },
      { en: 'public services', ru: 'общественные услуги', ex: 'Taxes fund public services.' },
      { en: 'to alleviate', ru: 'облегчать', ex: 'New metro lines could alleviate congestion.' },
      { en: 'infrastructure', ru: 'инфраструктура', ex: 'Rural areas need better infrastructure.' },
      { en: 'community spirit', ru: 'чувство общности', ex: 'Local festivals build community spirit.' },
      { en: 'inequality', ru: 'неравенство', ex: 'Education can reduce social inequality.' },
    ],
  },
];
